version: '3'
services:
  SQLServer:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_2019
    user: '0:0'
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 'Heck068*'
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    volumes:
      - './docker/mssql/data/:/var/opt/mssql'